### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
First of all: congrats for the interesting project, when this library will be a more-than-stable project it could be used for so much things! :)

This PR isn't for new things because I think some reviews must be done before continue on it:
- [x] composer.json: it wasn't valid (missing description) and the autoloader could be splitted
- [x] sorted keys (and namespaces): the code could increment very much after next features, so a bit of order imho is never a bad thing
- [x] PSR-\* standard: this is the only thing touched internal logic, but it's safe because most of the changes are really small
- [x] PHPDoc documentation: I'm still studying this project internal logic, so currently there's only a skeleton of the necessary PHPDoc for the community

Let me know if it's interesting for you, not interesting, something must be changed, I did errors on params types, etc..
Thanks

### CODE REVIEW

**Comment by RobinBressan** [comment]
Hi,

Thanks for your congrats. I never found time to finish this project, and I wrote it the fastest I could to prove that the concept was good, so I can understand you found things to improve :)

Your tasks seems good to me, but I am not familiar with the `Object Calisthenics` notion. It would be better to do this in another PR to avoid too much noise from the coding style / doc review here.
And I guess the benefit of it will be more understandable after reading the first changes.

Anyway thanks for your interest ! Because I don't much have time right now to work on the project.

**Comment by EmanueleMinotto** [comment]
Updated PR description without Object Calisthenics :+1:
You'll see my updates here and I'll ping you when finished (hope soon hehe).

**Comment by EmanueleMinotto** [comment]
@RobinBressan even after a long time I'm not able to document everything under `src/` properly, anyway  something was done and could be useful for people using IDEs.
Better than nothing imo ^^' hehe

**Comment by RobinBressan** [comment]
Thanks for that!

**Pull request merged**
